Test 2 / Add several random products and verify they are displayed correctly
xcervi/playwright_tests_with_po pull request #2
Opened 2024-07-09 11:57 UTC by xcervi

Conducted the task of Test 2:
1. Add several random products to the Shopping Cart 
2. Verify products are displayed correctly (check Name, Description, and Price values)

2024-07-09 15:28 UTC, AlinaZhykharieva requested changes

2024-07-09 15:28 UTC, AlinaZhykharieva commented on src/pages/Inventory.page.js
> +        const addButton = item.locator('[id^="add-to-cart"]');
why do we not have a getter for this element?

2024-07-09 15:28 UTC, AlinaZhykharieva commented on src/tests/inventory.spec.js
> +        expect(pricesHtoL).toEqual(sortedPricesHtoL);
It would be better to have one parametrized test for each sorting, now if first check fail you will not know if other cases work correctly

2024-07-09 15:28 UTC, AlinaZhykharieva commented on src/tests/inventory.spec.js
> +        const numberOfItemsToAdd = Math.floor(Math.random() * 5) + 1;
if number of items changed to less on-page here may be difficulties

2024-07-09 15:28 UTC, AlinaZhykharieva commented on src/tests/inventory.spec.js
> +            });
here the logic a bit complex, need to think how we can simplify

2024-07-10 20:36 UTC, hlazkov commented on src/tests/inventory.spec.js
> +        const numberOfItemsToAdd = Math.floor(Math.random() * itemNamesArray.length) + 1;
```suggestion
        const numberOfItemsToAdd = Math.floor(Math.random() * (itemNamesArray.length - 1)) + 1;
```

2024-07-10 20:37 UTC, hlazkov commented on src/tests/inventory.spec.js
> +        function getRandomUniqueIndexes(count) {
I would move this function to utils since its not related to test itself.

2024-07-10 20:39 UTC, hlazkov approved these changes
A few minor things to improve before its merged. Good job here!

2024-07-11 14:37 UTC, merged